### ISSUE TITLE
[Epic] Alpha Roadmap

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/auth-client-js#1]
## Resources

- [Auth Spec](https://github.com/WalletConnect/walletconnect-specs/tree/main/auth)
- [Auth Client API](https://github.com/WalletConnect/walletconnect-specs/blob/main/auth/client-api.md)

## Critical Path

This is intended as an overview of critical path work to get to an alpha state with the JS Auth SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

- [x] Set up `AuthClient` class
- [x] Pull in `@walletconnect/core`
- [x] Set up logging
- [x] Set up AuthEngine and `AuthEngine.init`
- [x] `IAuthClient` interfaces and types
- [x] `IAuthEngine` interfaces and types
- [x] Specify RPC method types
- [x] Set up Relayer events handling
- [x] Storage handling and storage key namespacing via `Core.Store` (e.g. `pairing`, `pending_request`, `settled_request`)
- [x] #2 
- [x] #4
- [x] Implement associated event handlers (`on("auth_request",...)`, `on("auth_response",...)`
- [x] #7 
- [x] Implement getters (`AuthClient.getPendingRequests`, `AuthClient.getRequest`)
- [x] Implement expirer logic
- [x] Update implementation to reflect these adjustments in spec once this is merged: https://github.com/WalletConnect/walletconnect-specs/pull/104
- [x] Implement metadata (#17)
- [x] #15 
- [x] Handle existing pairing flow #22 
- [x] Implement initial validation logic (#18)
- [ ] Implement error codes according to spec
- [x] Implement `client.getPairings` #36
- [x] Implement `client.disconnect` #36
- [x] Implement `client.ping` #40
